services:
  locci-url-api:
    image: ranckosolutionsinc/locci-url-api:v1.0.0
    container_name: locci-url-api
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_AUTH_TOKEN=${DATABASE_AUTH_TOKEN}
      - BASE_URL=${BASE_URL}
    networks:
      - locci-url-service

networks:
  locci-url-service:
    name: locci-url-service
        